name: maxim_chat
description: "A new Flutter project."
publish_to: "none"

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  firebase_database: ^12.0.1
  provider: ^6.1.5+1
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  firebase_core: ^4.1.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
